[package]
name = "affiliate"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "affiliate"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
mercurial-vault = { git="https://github.com/mercurial-finance/mercurial_sdk", features= ["cpi"], rev="35aa85f8aff7e1ab64b7276a6e4157223c3533bc"  }
vipers = "2.0.2"

[dev-dependencies]
solana-program-test = "1.9.17"
solana-sdk = "1.9.17"
assert_matches = "1.5.0"
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
spl-associated-token-account = "1.0.3"
solana-program = "1.9.17"
bincode = "1.3.3"